### PR TITLE
Remove unnecessary Guava dependency

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
@GLundh Could this please be released? We need a new release of this plugin to fix BOM Plugin Compatibility Tester (PCT) failures as seen in jenkinsci/bom#719.

**Comment by basil** [comment]
CC @hagzag @rsandell who also have release permissions on this repository :pray:

**Comment by GLundh** [comment]
Additional maintainers would be nice for this plugin. Is this something Cloudbees are willing to do?

**Comment by basil** [comment]
Not sure if you were addressing me specifically or not, but I don't work at CloudBees so I can't comment.

**Comment by GLundh** [comment]
I was hoping @rsandell could comment on it :) Since he was already pinged into this discussion. Sorry, should be clearer.

But if you are up for it @basil, please let me know :)

**Comment by hagzag** [comment]
@basil will try an look at this later today, just got back today and reached this thread.
and in if you are up for it like @rsandell says ...

**Pull request merged**
