### PR TITLE
RebuildAction.java : Make sure that a single instance of UserIDCause …

### PR DESCRIPTION
**Pull request by franknarf8**
…and RebuildCause are added to the build causes

- Fixes regression introduced in https://github.com/jenkinsci/rebuild-plugin/pull/56
- Added unit test

### CODE REVIEW

**Comment by franknarf8** [comment]
Not sure who to call in on this; but it seems like there is an infrastructure problem with the build system checking this. How do we relaunch a build? @GLundh

**Comment by GLundh** [comment]
@franknarf8  Do a "commit --amend" and push again. Should retrigger the CI.

**Comment by franknarf8** [comment]
@GLundh Should we do a new release for this fix?
The merged build seems to have failed for build environment reasons : https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Frebuild-plugin/detail/master/6/

**Comment by GLundh** [comment]
Thanks for the reminder @franknarf8 . I'll issue a release right now.

**Pull request merged**
