### PR TITLE
Fix wrong usage of CauseAction, rename some method + Fix unit test

### PR DESCRIPTION
**Pull request by franknarf8**
Contains the fix of the following pull request : https://github.com/jenkinsci/rebuild-plugin/pull/54
And a fix for the broken unit test

### CODE REVIEW

**Comment by franknarf8** [comment]
@tianzhipeng-git @GLundh

**Comment by franknarf8** [comment]
@GLundh Thanks a lot!

Could we do a new release of this repo?

Thanks in advance!

**Comment by GLundh** [comment]
I'll try to get a new release out this weekend.

**Comment by kapoorlakshya** [comment]
Hi @franknarf8 @GLundh  - I think I've found a bug introduced by this change in the v1.30 release. Here's what's happening:

In v1.29:
When user B rebuilds user A's job, the $BUILD_USER is updated to user B.

In v1.30:
Now when user B rebuilds user A's job, the $BUILD_USER is still A.

I am on Jenkins v2.164.1 and I am reading the build user using the [Build User Vars](https://wiki.jenkins.io/display/JENKINS/Build+User+Vars+Plugin) plugin. Please let me know if I can provide any other information to troubleshoot this. Thank you!

**Comment by marble-ma** [comment]
saw same issue as @kapoorlakshya

**Comment by kapoorlakshya** [comment]
Another change I noticed in v1.30 is this:

image

It lists the rebuild history (parent, grandparent build, and so on) instead of just the "parent" one. From v1.29 for comparison:

image

**Comment by eryajf** [comment]
> 您好@ franknarf8 @GLundh - 我想我发现v1.30版本中此更改引入了一个错误。这是发生了什么：
> 
> 在v1.29中：
> 当用户B重建用户A的作业时，$ BUILD_USER将更新为用户B.
> 
> 在v1.30中：
> 现在当用户B重建用户A的作业时，$ BUILD_USER仍为A.
> 
> 我在Jenkins v2.164.1上，我正在使用[Build User Vars](https://wiki.jenkins.io/display/JENKINS/Build+User+Vars+Plugin)插件阅读构建用户。如果我能提供任何其他信息来解决此问题，请告知我们。谢谢！


I also encountered the same problem

**Pull request merged**
