### PR TITLE
Handle case where last completed build does not have RebuildAction

### PR DESCRIPTION
**Pull request by sghill**
This fixes a NPE introduced in #155. We've run into this issue while attempting to view job config history with the latest version, and have pinned to the previous version to avoid it.

### Testing done

I attempted to create a tests with mockito that covered the logic of `RebuildLastCompletedBuildAction#getUrlName()`, but ran into issues with `Jenkins.instance` missing. Since the change here is straightforward, I wasn't sure it warranted creating `JenkinsRule` tests.

<details>
<summary><code>RebuildLastCompletedBuildActionTest.java</code></summary>

<pre>
package com.sonyericsson.rebuild;

import hudson.model.AbstractProject;
import hudson.model.FreeStyleBuild;
import hudson.model.FreeStyleProject;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.mockito.BDDMockito.given;

@RunWith(MockitoJUnitRunner.class)
public class RebuildLastCompletedBuildActionTest {
    @Mock
    private AbstractProject<FreeStyleProject, FreeStyleBuild> project;
    @Mock
    private FreeStyleBuild lastCompletedBuild;
    @Mock
    private RebuildAction rebuildAction;
    private RebuildLastCompletedBuildAction action;

    @Before
    public void setUp() {
        action = new RebuildLastCompletedBuildAction(project);
    }

    @Test
    public void shouldReturnNullIfNotBuildable() {
        given(project.isBuildable()).willReturn(false);
        String actual = action.getUrlName();
        assertNull(actual);
    }

    @Test
    public void shouldReturnNullIfNoLastCompletedBuild() {
        given(project.isBuildable()).willReturn(true);
        given(project.getLastCompletedBuild()).willReturn(null);
        String actual = action.getUrlName();
        assertNull(actual);
    }

    @Test
    public void shouldReturnNullIfNoRebuildActionOnLastCompletedBuild() {
        given(project.isBuildable()).willReturn(true);
        given(project.getLastCompletedBuild()).willReturn(lastCompletedBuild);
        given(lastCompletedBuild.getAction(RebuildAction.class)).willReturn(null);
        String actual = action.getUrlName();
        assertNull(actual);
    }

    @Test
    public void shouldReturnUrlName() {
        given(project.isBuildable()).willReturn(true);
        given(project.getLastCompletedBuild()).willReturn(lastCompletedBuild);
        given(rebuildAction.getUrlName()).willReturn("expected-task-url");
        given(lastCompletedBuild.getAction(RebuildAction.class)).willReturn(rebuildAction);
        String expected = "lastCompletedBuild/expected-task-url";
        String actual = action.getUrlName();
        assertEquals(expected, actual);
    }
}
</pre>
</details>

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by sghill** [comment]
@daniel-beck it's a `hudson.model.FreeStyleProject` that was created before the upgrade. Loading up `{buildUrl}/jobConfigHistory/` showed this stacktrace:

```
Caused by: java.lang.NullPointerException: Cannot invoke "com.sonyericsson.rebuild.RebuildAction.getTaskUrl()" because "action" is null
        at com.sonyericsson.rebuild.RebuildLastCompletedBuildAction.getUrlName(RebuildLastCompletedBuildAction.java:61)
        at hudson.model.Actionable.getDynamic(Actionable.java:345)
        at hudson.model.Job.getDynamic(Job.java:864)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
```

**Comment by daniel-beck** [comment]
My guess is you have a plugin installed that provides an implementation of `RebuildValidator`, like `GerritTrigger`. That's a case I didn't test for as I was unaware this existed.

**Review by GLundh — APPROVED** [review]

**Comment by GLundh** [comment]
@daniel-beck: Regardless, I don't see much risk for this PR. But before I merge & close, do you see a risk?

**Comment by daniel-beck** [comment]
@GLundh Untested but seems fine if it works. Feedback was exclusively about understanding how this happens.

**Comment by pci-mthompson** [comment]
FYI, this can also occur with inheritance builds (Project Inheritance Plugin) after recent updates.  I manually patched a version of rebuild and this PR fixes it.

**Comment by shemuwel** [comment]
Hello! Any chance to get this PR merged?
Thank you

**Review by hagzag — APPROVED** [review]
LGTM

**Comment by timotei** [comment]
@hagzag can we make use of this fix in a **released** version? We're currently blocked from rolling out the latest update because of this issue.

**Pull request merged**
